# Generated by Django 6.0.2 on 2026-04-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_applicationnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationnote',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job_title',
            new_name='role',
        ),
    ]
