# Generated by Django 6.0.2 on 2026-04-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_applicationnote_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='statushistory',
            options={'ordering': ['-changed_at']},
        ),
    ]
